replace media sources:
  - replace: /mnt/datacore/projects/
    with: ''
  - replace: /home/ewen/projects/
    with: ''

extract colors:
  enabled: true

make thumbnails:
  enabled: true
  sizes: [400, 700, 1200]
  file name template: out/media/<parent>/<media id>@<size>.webp

copy media:
  to: out/media/

build metadata file: conf/.lastbuild.yaml
