validate:
  checks:
    schema compliance: fatal
    work folder uniqueness: fatal
    work folder safeness: error
    yaml header: error
    title presence: error
    title uniqueness: error
    tags presence: fatal
    tags knowledge: error
    working media: warn
    working urls: off

build steps:
  extract colors:
    enabled: yes
