[package]
name = "ortfodb"
version = "1.4.0"
edition = "2021"
description = "An ortfodb (https://github.com/ortfo/db) client library for Rust."
license = "MIT"
repository = "https://github.com/ortfo/db"
homepage = "https://github.com/ortfo/db/tree/main/packages/rust"

[dependencies]
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
