name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - uses: extractions/setup-just@v2

    - name: Verify dependencies
      run: go mod verify

    - name: Build CLI package
      run: just build
