name: Update docs website

on:
    release:
        types: [published]
    push:
        branches: [main]
        paths: [CHANGELOG.md] # update Unreleased section of changelog
    workflow_dispatch:

jobs:
    update-docs:
        runs-on: ubuntu-latest
        permissions:
            repository-projects: write
        steps:
            - name: Trigger submodule update on docs
              uses: peter-evans/repository-dispatch@v3
              with:
                token: ${{ secrets.PAT_PUSH_TO_ORTFO_WEBSITE }}
                event-type: update-submodule
                repository: ortfo/website
                client-payload: >
                    {
                        "sha": "${{github.sha}}",
                        "module": "ortfodb"
                    }
