name: Update docs website

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger submodule update on docs
              uses: peter-evans/repository-dispatch@v3
              with:
                event-type: update-submodule
                repository: ortfo/website
                client-payload: >
                    {
                        "sha": "${{github.sha}}",
                        "module": "ortfodb",
                    }
